[package]
name = "unlock_some_binary"
version = "0.1.0"
edition = "2021"
authors = ["Antoine Reversat"]

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
rusb = "0.9.4"
